_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": D
              "6":
                - 3
              "7": []
        python_version: 3.12.8
        t:
            "1":
                - 12
                - 45
                - 55
            "2":
                - 12
                - 45
                - 55
            "3":
                - 7
                - 16
                - 23
                - 55
                - 62
            "4": 3.12.8
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
ACTIVATION:
    value: tanh
ANNEAL_LR:
    value: false
CONST_NORMALIZE_OBS:
    value: true
DATA_NOISE:
    value: 0
DEBUG:
    value: false
ENV_NAME:
    value: hopper
FOLDER:
    value: ../results/
GAMMA:
    value: 0.99
GREEDY_ACT:
    value: false
LR:
    value: 0.005
MAX_GRAD_NORM:
    value: 0.5
NORMALIZE_OBS:
    value: false
NORMALIZE_REWARD:
    value: true
NUM_ENVS:
    value: 4
NUM_STEPS:
    value: 1024
OVERFIT:
    value: false
OVERFIT_SEED:
    value: 0
PROJECT:
    value: Policy Distillation
SEED:
    value: 1337
UPDATE_EPOCHS:
    value: 400
WIDTH:
    value: 512
es_config:
    value:
        dataset_size: 64
        log_interval: 1
        lrate_init: 0.05
        n_generations: 2000
        popsize: 2048
        rollouts_per_candidate: 2
        save_interval: 10
        sigma_decay: 1
        sigma_init: 0.03
